name: Parsec download

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  parsec-flat-windows32:
    runs-on: windows-latest
    steps:
      - name: Download Parsec
        shell: pwsh
        run: Invoke-WebRequest "https://builds.parsecgaming.com/package/parsec-flat-windows.zip" -OutFile test.zip
